### ISSUE TITLE
Broken if statements

### ISSUE THREAD

**Issue by RedstoneWizard08** [ISB3DPRINTERS/automated-server#5]
All of these will always be true, as all the statement does is it checks if the variable was set.

https://github.com/ISB3DPRINTERS/automated-server/blob/58eea7303c7421d06565a3c65e4fc868bc1807d1/src/api/functions.ts#L52
https://github.com/ISB3DPRINTERS/automated-server/blob/58eea7303c7421d06565a3c65e4fc868bc1807d1/src/api/functions.ts#L60
https://github.com/ISB3DPRINTERS/automated-server/blob/58eea7303c7421d06565a3c65e4fc868bc1807d1/src/api/functions.ts#L62
https://github.com/ISB3DPRINTERS/automated-server/blob/58eea7303c7421d06565a3c65e4fc868bc1807d1/src/api/functions.ts#L64
https://github.com/ISB3DPRINTERS/automated-server/blob/58eea7303c7421d06565a3c65e4fc868bc1807d1/src/api/functions.ts#L66
https://github.com/ISB3DPRINTERS/automated-server/blob/58eea7303c7421d06565a3c65e4fc868bc1807d1/src/api/functions.ts#L68
https://github.com/ISB3DPRINTERS/automated-server/blob/58eea7303c7421d06565a3c65e4fc868bc1807d1/src/api/functions.ts#L70
https://github.com/ISB3DPRINTERS/automated-server/blob/58eea7303c7421d06565a3c65e4fc868bc1807d1/src/api/functions.ts#L72
https://github.com/ISB3DPRINTERS/automated-server/blob/58eea7303c7421d06565a3c65e4fc868bc1807d1/src/api/functions.ts#L74
https://github.com/ISB3DPRINTERS/automated-server/blob/58eea7303c7421d06565a3c65e4fc868bc1807d1/src/api/functions.ts#L78

**Comment by ravinder-Olivier** [comment]
Thanks for the catch, never noticed that. Will be fixed in next commit
